### ISSUE TITLE
[Feature Request] Add a new page to show the whole Inheritance Relationship

### ISSUE THREAD

**Issue by TechQuery** [valerii-zinchenko/jsdoc-inheritance-diagram#1]
Could you add an independent page in document to show a big diagram ?

**Comment by valerii-zinchenko** [comment]
Hi! Yes, I also found, that to see the whole diagram would be great. I will work on that.

**Comment by valerii-zinchenko** [comment]
Hi @TechQuery !
Sorry for a long delay. I updated the generator and the plugin for diagram. Please try `jsdoc-inheritance-diagram@v1.2.1`
