### ISSUE TITLE
Unreferenced nodes when pertaining to a namespace

### ISSUE THREAD

**Issue by daguhl** [valerii-zinchenko/jsdoc-inheritance-diagram#2]
Referencing nodes from a namespace doesn't work:
```
some.A = class { ..}
some.B class extends some.A {...}
```

Reason: in index.js ```addClass(doclet)```, use doclet longname instead of short name as reference.

Fix:
```
diff index.js fixed-index.js 
14c14
< 	const name = doclet.name;
---
> 	const name = doclet.longname;
```

**Comment by valerii-zinchenko** [comment]
Hi @daguhl ! Thanks, that you found it and suggested the fix. I applied the fix and published the new version v1.2.2
