### ISSUE TITLE
Extra Undefined text appended to graph

### ISSUE THREAD

**Issue by daguhl** [valerii-zinchenko/jsdoc-inheritance-diagram#3]
In some cases a```undefined```text element follows the diagrams closing ```</div>```.

Reason: When ```doclet.description``` is undefined in ```parseComplete()```.

Fix:
```
diff index.js fixed-index.js 
91c91
< 			doclet.description = '<div class="class-diagram">' + diagram.getResult() + '</div>' + doclet.description;
---
> 			doclet.description = '<div class="class-diagram">' + diagram.getResult() + '</div>' + (doclet.description || '');
```

**Comment by valerii-zinchenko** [comment]
Thanks. The fix is applied and the the new version v1.2.2 is published with it.

**Comment by daguhl** [comment]
Hi Valerii,

Thanks for your work. Given that we can't write to your repos, we created a
local fork of jsdoc-inheritance-diagram. Once we're done we'll send you
change suggestions and switch back to your repository if you merge them But
the best and faster way would be to give me rights on jsdoc-inheritance-diagram
and inheritance-diagram to create branches and pull requests, while you
keep full control of the repos and master branch.

David

**Comment by valerii-zinchenko** [comment]
Hi David,

I think, you can fork any public repository (there is a button "Fork" on top), make changes in your forked repo and create pull requests. As far as I know, you can create as many pull requests as you want from your forked repo. Have you tried that?

Valerii

**Comment by daguhl** [comment]
Ah ok I will try this when needed.

Thanks
David
